// <auto-generated />
using System;
using GFL.TestTask.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GFL.TestTask.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GFL.TestTask.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Creating Digital Images"
                        },
                        new
                        {
                            Id = 2,
                            ParentId = 1,
                            Title = "Resources"
                        },
                        new
                        {
                            Id = 3,
                            ParentId = 1,
                            Title = "Evidence"
                        },
                        new
                        {
                            Id = 4,
                            ParentId = 1,
                            Title = "Graphic Products"
                        },
                        new
                        {
                            Id = 5,
                            ParentId = 2,
                            Title = "Primary Sources"
                        },
                        new
                        {
                            Id = 6,
                            ParentId = 2,
                            Title = "Secondary Sources"
                        },
                        new
                        {
                            Id = 7,
                            ParentId = 4,
                            Title = "Process"
                        },
                        new
                        {
                            Id = 8,
                            ParentId = 4,
                            Title = "Final Producty"
                        });
                });

            modelBuilder.Entity("GFL.TestTask.Models.Folder", b =>
                {
                    b.HasOne("GFL.TestTask.Models.Folder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GFL.TestTask.Models.Folder", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
